version: '3.8'

services:
  mongo:
    image: docker.io/mongo:latest
    environment:
      # ROOT USER
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
      - MONGO_CUSTOM_USERNAME=${MONGO_CUSTOM_USER}
      - MONGO_CUSTOM_PASSWORD=${MONGO_CUSTOM_PASSWORD}
    volumes:
      # database storage
      - mongo-data:/data
      # init scripts
      - ./db-migration/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    hostname: mongo
    restart: "no"
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    environment:
      - REDIS_HOST=${REDIS_HOST_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

volumes:
  mongo-data: {}
  cache:
    driver: local